'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Mask
    Public Property MaskId As Integer
    Public Property MaskName As String
    Public Property Shortcut As String
    Public Property DeviceName As String
    Public Property Flat As String
    Public Property Description As String

    Public Overridable Property Wafers As ICollection(Of Wafer) = New HashSet(Of Wafer)

End Class
