'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProcessSequence
    Public Property ProcessSequenceId As Integer
    Public Property Index As Integer
    Public Property Process_ProcessId As Integer
    Public Property ProcessGroup_ProcessGroupId As Integer

    Public Overridable Property ProcessGroup As ProcessGroup
    Public Overridable Property Process As Process

End Class
