'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SPCDataType
    Public Property SPCDataTypeId As Integer
    Public Property Description As String
    Public Property Remark As String

    Public Overridable Property SPCDatas As ICollection(Of SPCData) = New HashSet(Of SPCData)

End Class
