'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Wafer
    Public Property WaferId As Integer
    Public Property WaferIdentification As String
    Public Property WaferLotNo As String
    Public Property WaferNo As String
    Public Property EPIRunNumber As String
    Public Property EPIDeliveryDate As Nullable(Of Date)
    Public Property Remark As String
    Public Property WaferSupplier_WaferSupplierId As Nullable(Of Integer)
    Public Property EpiSupplier_EPISupplierId As Nullable(Of Integer)
    Public Property WaferType_WaferTypeId As Nullable(Of Integer)
    Public Property WaferSize_WaferSizeId As Nullable(Of Integer)
    Public Property Mask_MaskId As Nullable(Of Integer)
    Public Property Product_ProductId As Nullable(Of Integer)
    Public Property ProductGroup_ProductGroupId As Nullable(Of Integer)
    Public Property WaferState_WaferStateId As Nullable(Of Integer)
    Public Property Lot_LotId As Nullable(Of Integer)
    Public Property EpiType_EpiTypeId As Nullable(Of Integer)
    Public Property FailureCategory_FailureCategoryId As Nullable(Of Integer)

    Public Overridable Property Lot As Lot
    Public Overridable Property Mask As Mask
    Public Overridable Property WaferState As WaferState
    Public Overridable Property WaferSupplier As WaferSupplier
    Public Overridable Property Product As Product
    Public Overridable Property ProductGroup As ProductGroup
    Public Overridable Property FailureCategory As FailureCategory
    Public Overridable Property SPCAcquisitions As ICollection(Of SPCAcquisition) = New HashSet(Of SPCAcquisition)
    Public Overridable Property EpiSupplier As EpiSupplier
    Public Overridable Property EpiType As EpiType
    Public Overridable Property WaferSize As WaferSize
    Public Overridable Property WaferType As WaferType
    Public Overridable Property WaferHistories As ICollection(Of WaferHistory) = New HashSet(Of WaferHistory)

End Class
