'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Layer
    Public Property LayerId As Integer
    Public Property Description As String
    Public Property Acronym As String
    Public Property Duration As Nullable(Of Integer)
    Public Property LocationId As Nullable(Of Integer)

    Public Overridable Property ProcessSequences As ICollection(Of ProcessSequence) = New HashSet(Of ProcessSequence)

End Class
