'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProcessGroup
    Public Property ProcessGroupId As Integer
    Public Property GroupDescription As String
    Public Property Options As String
    Public Property BaseMaterial As String
    Public Property TargetDuration As Nullable(Of Integer)
    Public Property ProductName_ProductNameId As Integer

    Public Overridable Property ProductName As ProductName
    Public Overridable Property ProcessSequences As ICollection(Of ProcessSequence) = New HashSet(Of ProcessSequence)

End Class
