'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ProcessSequence
    Public Property ProcessSequenceId As Integer
    Public Property GroupId As Nullable(Of Integer)
    Public Property Index As Nullable(Of Integer)
    Public Property Layer_LayerId As Nullable(Of Integer)
    Public Property ProcessGroup_ProcessGroupId As Integer

    Public Overridable Property Layer As Layer
    Public Overridable Property ProcessGroup As ProcessGroup

End Class
