'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SPCData
    Public Property SPCDataId As Integer
    Public Property SPCAqcuisitionId As Nullable(Of Integer)
    Public Property Value As Nullable(Of Double)
    Public Property Position As Nullable(Of Double)
    Public Property SPCDataType_SPCDataTypeId As Integer

    Public Overridable Property SPCAcquisition As SPCAcquisition
    Public Overridable Property SPCDataType As SPCDataType

End Class
