'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class WaferHistory
    Public Property WaferHistoryId As Integer
    Public Property StartDate As Nullable(Of Date)
    Public Property StopDate As Nullable(Of Date)
    Public Property LayerId As Nullable(Of Integer)
    Public Property Number As Nullable(Of Integer)
    Public Property TechnicianId As Nullable(Of Integer)
    Public Property Text As String
    Public Property Remark As String
    Public Property Technician_TechnicianId As Integer
    Public Property WaferLocation_WaferLocationId As Integer
    Public Property Wafer_WaferID As Integer

    Public Overridable Property Technician As Technician
    Public Overridable Property Wafer As Wafer
    Public Overridable Property WaferLocation As WaferLocation

End Class
